### ISSUE TITLE
Allow use of logging tags in source and sourcetype fields

### ISSUE THREAD

**Issue by jeffywu** [splunk/docker-logging-plugin#52]
**What would you like to be added**:
When running docker compose I would like to be able to set the source and sourcetype using the logging tags: https://docs.docker.com/v17.09/engine/admin/logging/log_tags/. This way I can set up a default logging config and have it applied to all my containers:
```
x-logging:
  &default-logging
  driver: "splunk"
  options:
    splunk-token: "12345678-ABCD-EFGH-IJKL-123456789012"
    splunk-url: "https://localhost:8088"
    splunk-sourcetype: "docker:{{.Name}}"
    splunk-source: "{{.Name}}-{{.ID}}"
    tag: "{{.Name}}-{{.ID}}
```

**Why is this needed**:
The alternative is to manually set the source and sourcetype on each container in the compose file which is not very user friendly.
